Repository RVCorp/GamesToGo, pull requests merged in 2021-05, with the labels that each got.

#64 Fix room creation/joining crashing if a zip needed to be opened
  .idea/.idea.GamesToGo/.idea/modules.xml
  GamesToGo.Android/GamesToGo.Android.csproj
  GamesToGo.Android/MainActivity.cs
  GamesToGo.Android/Properties/AndroidManifest.xml
  GamesToGo.Game/GamesToGo.Game.csproj
  GamesToGo.Game/GamesToGoGame.cs
Labels: bug

#65 Fix Mole's review
  GamesToGo.Common/Game/Tag.cs
  GamesToGo.Editor/Graphics/ElementVisualEditorContainer.cs
  GamesToGo.Editor/Graphics/ProjectObjectEventContainer.cs
  GamesToGo.Editor/Graphics/PublishedProjectSummaryContainer.cs
  GamesToGo.Editor/Project/Actions/GivePlayerXCardsFromTileAction.cs
Labels: invalid

#66 Fix Log out in not working
  GamesToGo.Common/Online/APIController.cs
  GamesToGo.Game/Overlays/LoginOverlay.cs
Labels: bug

#67 IDK
  GamesToGo.Editor/Project/Events/ProjectEvent.cs
  GamesToGo.Editor/Screens/ProjectObjectScreen.cs
  GamesToGo.Game/Graphics/BoardsContainer.cs
  GamesToGo.Game/Graphics/CardContainer.cs
  GamesToGo.Game/Graphics/PlayerHandContainer.cs
  GamesToGo.Game/Graphics/PlayerPreview.cs
  GamesToGo.Game/Graphics/TagContainer.cs
  GamesToGo.Game/Graphics/TestContainer.cs
  GamesToGo.Game/Graphics/TileContainer.cs
  GamesToGo.Game/Graphics/TokenContainer.cs
  GamesToGo.Game/LocalGame/Elements/Board.cs
  GamesToGo.Game/LocalGame/Elements/Card.cs
  GamesToGo.Game/LocalGame/Elements/ElementOrientation.cs
  GamesToGo.Game/LocalGame/Elements/IHasElements.cs
  GamesToGo.Game/LocalGame/Elements/Tile.cs
  GamesToGo.Game/LocalGame/Elements/Token.cs
  GamesToGo.Game/LocalGame/GameElement.cs
  GamesToGo.Game/Online/InvitationsUpdater.cs
  GamesToGo.Game/Online/Models/OnlineProjectElements/OnlineCard.cs
  GamesToGo.Game/Online/Models/OnlineProjectElements/OnlineTile.cs
  GamesToGo.Game/Online/Models/RequestModel/Invitation.cs
  GamesToGo.Game/Online/Models/RequestModel/OnlineRoom.cs
  GamesToGo.Game/Online/Models/RequestModel/PlayerStatus.cs
  GamesToGo.Game/Online/Models/RequestModel/Report.cs
  GamesToGo.Game/Online/Models/RequestModel/ReportType.cs
  GamesToGo.Game/Online/Models/RequestModel/Statistic.cs
  GamesToGo.Game/Online/PollingComponent.cs
  GamesToGo.Game/Online/Requests/AvailableReportsRequest.cs
  GamesToGo.Game/Online/Requests/CreateRoomRequest.cs
  GamesToGo.Game/Online/Requests/GetProjectRequest.cs
  GamesToGo.Game/Online/Requests/IgnoreInvitationRequest.cs
  GamesToGo.Game/Online/Requests/ReportGameRequest.cs
  GamesToGo.Game/Online/Requests/SearchTagRequest.cs
  GamesToGo.Game/Online/Requests/SendArgumentRequest.cs
  GamesToGo.Game/Online/Requests/UploadUserImageRequest.cs
  GamesToGo.Game/Overlays/InvitationsOverlay.cs
  GamesToGo.Game/Overlays/LoginOverlay.cs
  GamesToGo.Game/Overlays/SearchOverlay.cs
  GamesToGo.Game/Overlays/SelectionOverlay.cs
  GamesToGo.Game/Overlays/SideMenuOverlay.cs
  GamesToGo.Game/Screens/GameInfoScreen.cs
  GamesToGo.Game/Screens/GameScreen.cs
Labels: help wanted
